### ISSUE TITLE
penagihan berdasarkan purchase order

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#1]
- cetak recipet ketika penerimaan barang
- penagihan po dilenkapi dengan reciept.

**Comment by dwiluckyh** [comment]
Jika dalam kasus Supplier tidak dapat memenuhi pengiriman barang sesuai dg PO maka PO dapat dinyatakan CLOSE dan penagihan sesuai dg Print out Recieving yang dilakukan, karena secara otomatis juga Invoice tercreate berdasar total qty yang di recieving.

=CLOSED=
