### ISSUE TITLE
Pengaturan Output Print Reciept POS

### ISSUE THREAD

**Issue by dwiluckyh** [wahhid/project0021#13]
1. Penempatan Rupiah di depan angka, Contoh : Rp. XX.XXX,- termasuk  di tampilan POS & print Reciept
2. Hapus decimal atau Dua angka di belakang koma. 
3. Posisi Qty dan Harga barang diberi Jarak jangan terlalu dekat
4. menghilangkan keterangan shop: (nama wharehouse) di print reciept
5. menampilkan keterangan Description | Quantity | Price di header
6. Format tgl dan jam di print reciept diset DD/MM/YYYY dan 24h hh/mm/ss
7. Contoh Reciept terlampir

![reciept standart](https://cloud.githubusercontent.com/assets/13175056/24346044/f56c9ad8-12fc-11e7-8a72-39695a275ccf.jpg)

**Comment by dwiluckyh** [comment]
Update sudah di buat untuk nomor,
1. sudah
2. sudah
3. sudah
4. belum
5. belum
6. belum

**Comment by wahhid** [comment]
Sudah Diupdate semua
