### ISSUE TITLE
Format Print PO dan Receiving PO

### ISSUE THREAD

**Issue by dwiluckyh** [wahhid/project0021#16]
Untuk Recieving PO
format tanda tangan :

![image](https://cloud.githubusercontent.com/assets/13175056/24696210/e5df5232-1a12-11e7-9316-5592d0d98189.png)

Untuk Purchase Order
format tanda tangan : 

![image](https://cloud.githubusercontent.com/assets/13175056/24696253/062b392a-1a13-11e7-9b2e-e12682b7a0ef.png)

**Comment by wahhid** [comment]
Report Purchase Order sudah bisa diakses masih perlu finishing

**Comment by wahhid** [comment]
Report Delivery Slip sudah bisa diakses masih perlu finishing
