### ISSUE TITLE
Alert Picking Automatic

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#17]
Alert Picking Automatic

**Comment by dwiluckyh** [comment]
Pertanyaan:
Cara agar alertnya bisa otomatis terkirim keemail ke orang tertentu

Update2:

saat ini masih dicustom secara program, Nantinya akan ada menu untuk daftar email yang akan mendapat alert. (*saat ini alert belum bisa otomatis terkirim ke email user)
