### ISSUE TITLE
Inventory Adjustment with CSV FIle

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#21]
- Siapkan CSV file minimal dengan 2 field , product_name dan quantity
- lengkapi product_name dan quantity sesuai dengan stock
- masuk ke inventory adjustment
- Create New Inventory adjustment
- Pilih By File
- Kemudian upload file csv yang sudah di siapkan
- Kemudian process line
- kemudian validate

**Comment by dwiluckyh** [comment]
done closed
