### ISSUE TITLE
Printed Number

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#4]
Informasi Printed Number di SO, PO , INV, DO, Reciept

**Comment by dwiluckyh** [comment]
belum selesai dibuat.

**Comment by dwiluckyh** [comment]
untuk Printed Number belum selesai, akan digunakan untuk keterangan Print PO dan Receive PO.

**Comment by wahhid** [comment]
SO Done

**Comment by wahhid** [comment]
PO Done

**Comment by wahhid** [comment]
INV Done

**Comment by wahhid** [comment]
DO Done

**Comment by wahhid** [comment]
Receipt Done
