### ISSUE TITLE
Sales Order dari Asuransi

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#6]
Penentuan lokasi gudang untuk barang pembelian oleh Asuransi

**Comment by dwiluckyh** [comment]
Saat ada pembelian Sparepart oleh bengkel untuk asuransi melalui menu SO maka pengeluaran barang dari " Gudang Stock bisa dipilih ke Gudang Asuransi " belum selesai.

**Comment by dwiluckyh** [comment]
sudah diinfokan ke cust p Dwi dan Oke. menunggu program update..

**Comment by wahhid** [comment]
- Aktifkan advance routing pada warehouse
- buat location baru untuk asuransi dengan type customer
- customer asuransi diarahkan ke warehouse location
- tambahkan push rules pada my ship untuk asuransi warehouse location

**Comment by dwiluckyh** [comment]
Pertanyaan:
Saat Create Sales Order, Picking masih di Delivery Order customer umum bukan Asuransi

Update2:
-on check route
