### ISSUE TITLE
Menu Customer di Workshop

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#7]
Menu Customer di Workshop

**Comment by dwiluckyh** [comment]
Sudah ada menu Customer Vehicle di Workshop tetapi blm bisa create, dan keterangan nama dan identitas customer tidak ada di menu tsb.
![image](https://cloud.githubusercontent.com/assets/13175056/24343638/bacbd764-12f1-11e7-8402-3925317dfd5a.png)

**Comment by wahhid** [comment]
Done sudah ditambahkan partner field

**Comment by dwiluckyh** [comment]
Pertanyaan:
Ketika create customer member disubmenu workshop (Vehicle) ada pilihan memilih customer lg, dan yang keluar semua data contact (supplier,customer,dan user)

Update2:
Menu customer member disubmenu workshop, saat input Vehicle tidak perlu lg memilih customer karena secara langsung akan terinput sesuai customer yang sudah diisi.
