### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by wahhid** [wahhid/project0021#8]
Employee(nik)
Customer (Kode)
Supplier(kode)
Department (kode)

**Comment by dwiluckyh** [comment]
Employee(nik) = Belum
Customer (Kode) = Sudah
Supplier(kode) = Sudah
Department (kode) = Belum

**Comment by dwiluckyh** [comment]
Update
Customer (Kode)
Supplier(kode)

untuk Uniqe ID diatas kolom idny mandatory harus diisi Codenya, tetapi ketika sudah diisi dan disave ID td hilang dan tergenerate dg code WOCxxx

request cust jika mau generate otomatis kolom tsb tidak usah harus diisi dengan format IDnya
Venxxx atau Cusxxx

**Comment by wahhid** [comment]
Employee(nik) = Suda
Customer (Kode) = Sudah
Supplier(kode) = Sudah
Department (kode) = Sudah
