### ISSUE TITLE
Pembuatan Authorisasi user group berdasar View create Delete di setiap modul

### ISSUE THREAD

**Issue by dwiluckyh** [wahhid/project0021#9]
Setiap modul memiliki group hak akses yang terdiri dari : 
- View
- Create
- Delete

setiap user bisa diset sesuai dengan hak akses diatas.

akan dibuat setelah mendapat list user akses dari Andaru motor

**Comment by wahhid** [comment]
Done , sudah ada tinggal diatur per user
